[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-L.",
    "-C", "force-frame-pointers=yes"
]
linker = "rust-lld"
