[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
buddy_system_allocator = "0.6"
bitflags = "2.4"

[profile.release]
debug = true
strip = false
lto = true
opt-level = 2
panic = "abort"

[profile.dev]
panic = "abort"
